apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-test-1
spec:
  check_interval: "1"
  retry_interval: "1"
  notification_interval: "1"
  max_attempts: "3"
  escalation: "afrank@mozilla.com"
  template:
    spec:
      restart_policy: OnFailure
      containers:
      - name: test-1
        image: afrank/mozlenium:latest
        command: ["/app/entrypoint.sh"]
        args: ["/checks/test-check-1.js"]
        env:
          - name: SSO_LDAP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: site-checker-secrets
                key: SSO_LDAP_PASSWORD
        volumeMounts:
        - name: site-checks
          mountPath: "/checks"
          readOnly: true
      volumes:
      - name: site-checks
        secret:
          secretName: site-checks
