---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-test-1
  namespace: default
spec:
  check_interval: 1
  retry_interval: 1
  notification_interval: 1
  max_attempts: 5
  escalations:
  - type: email
    args:
      email: afrank@mozilla.com
  template:
    spec:
      restart_policy: Never
      containers:
      - name: test-1
        image: afrank/mozlenium:latest
        envFrom:
        - secretRef:
            name: check-test-1-mozlenium-secrets
        volumeMounts:
        - name: checks
          mountPath: "/checks"
          readOnly: true
      volumes:
      - name: checks
        secret:
          secretName: check-test-1-secret

---
# here is where you put any secrets you want your
# check to have. The secret value is base64-encoded
# For example: echo -n thisisnotsecret | base64 -w0
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: check-test-1-mozlenium-secrets
  namespace: default
data:
  SECRETSTUFF: dGhpc2lzbm90c2VjcmV0

---
# here is where you store the base64-encoded check script
# the blob was generated with:
# cat demo-check.js | base64 -w0 (on mac leave -w0 off)
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: check-test-1-secret
  namespace: default
data:
  demo-check.js: Ly9kZW1vIGNoZWNrCgpyZXF1aXJlKCdtb3psZW5pdW0nKSgpOwoKdmFyIGFzc2VydCA9IHJlcXVpcmUoJ2Fzc2VydCcpOwp2YXIgdXJsID0gJ2h0dHBzOi8vd3d3Lmdvb2dsZS5jb20nCgpjb25zb2xlLmxvZygic3RhcnRpbmcgY2hlY2siKTsKCiRicm93c2VyLmdldCh1cmwpOwoKY29uc29sZS5sb2coJHNlY3VyZS5TRUNSRVRTVFVGRik7Cgpjb25zb2xlLmxvZygid2VsbCB0aGF0IHdlbnQgZ3JlYXQiKTsKCg==
