---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-test-1
  namespace: default
spec:
  check_interval: 10s
  retry_interval: 1m
  notification_interval: 10m
  max_attempts: 5
  escalations:
  - type: email
    args:
      email: afrank@mozilla.com
  template:
    spec:
      restart_policy: Never
      containers:
      - name: test-1
        image: afrank/mozlenium:latest
        envFrom:
        - secretRef:
            name: check-test-1-mozlenium-secrets
        volumeMounts:
        - name: checks
          mountPath: "/checks"
          readOnly: true
      volumes:
      - name: checks
        configMap:
          name: check-test-1-cm

---
# here is where you put any secrets you want your
# check to have. The secret value is base64-encoded
# For example: echo -n thisisnotsecret | base64 -w0
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: check-test-1-mozlenium-secrets
  namespace: default
data:
  SECRETSTUFF: dGhpc2lzbm90c2VjcmV0

---
# here is the check itself, stored in a configmap
# this block was generated with 
# k create configmap check-test-1-cm --from-file=./demo-check.js
kind: ConfigMap
apiVersion: v1
metadata:
  name: check-test-1-cm
  namespace: default
data:
  demo-check.js: |+
    //demo check

    require('mozlenium')();

    var assert = require('assert');
    var url = 'https://www.google.com'

    console.log("starting check");

    $browser.get(url);

    console.log($secure.SECRETSTUFF);

    console.log("well that went great");

