apiVersion: v1
kind: Service
metadata:
  name: mozalert-controller
  labels:
    app: mozalert-controller
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None
  selector:
    app: mozalert-controller

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mozalert-controller
  name: mozalert-controller
  namespace: default
spec:
  replicas: 1
  serviceName: "mozalert-controller"
  selector:
    matchLabels:
      app: mozalert-controller
  template:
    metadata:
      labels:
        app: mozalert-controller
    spec:
      containers:
      - image: afrank/mozalert-controller:latest
        imagePullPolicy: Always
        name: mozalert-controller
      restartPolicy: Always
